export default /** @type {import("../../src/schema").RawDataset} */ ({
    name: "example-dataset",
    title: "Example Dataset",
    data: {
        "data-example": "data-example.json",
    },
    description:
        "This is a sample dataset generated by GPT-4o. Each conversation is a mock job interview (GPT-4o confused job interviews with research interviews, but this is an example anyway).",
    researchQuestion:
        "How was the interview process flowing between the interviewer and the interviewee?",
    codingNotes:
        "Please analyze, in detail, the emotional flow and power dynamics of the interview process.",
});
